cp ../merged/image11*.jpg content/images/ && git add . && git commit -m'Add first 1200 images' && git push
cp ../merged/image12*.jpg content/images/ && git add . && git commit -m'Add first 1300 images' && git push
cp ../merged/image13*.jpg content/images/ && git add . && git commit -m'Add first 1400 images' && git push
cp ../merged/image14*.jpg content/images/ && git add . && git commit -m'Add first 1500 images' && git push
cp ../merged/image15*.jpg content/images/ && git add . && git commit -m'Add first 1600 images' && git push
cp ../merged/image16*.jpg content/images/ && git add . && git commit -m'Add first 1700 images' && git push
cp ../merged/image17*.jpg content/images/ && git add . && git commit -m'Add first 1800 images' && git push
cp ../merged/image18*.jpg content/images/ && git add . && git commit -m'Add first 1900 images' && git push
cp ../merged/image19*.jpg content/images/ && git add . && git commit -m'Add first 2000 images' && git push
cp ../merged/image20*.jpg content/images/ && git add . && git commit -m'Add first 2100 images' && git push
cp ../merged/image21*.jpg content/images/ && git add . && git commit -m'Add first 2200 images' && git push
cp ../merged/image22*.jpg content/images/ && git add . && git commit -m'Add first 2300 images' && git push
cp ../merged/image23*.jpg content/images/ && git add . && git commit -m'Add first 2400 images' && git push
cp ../merged/image24*.jpg content/images/ && git add . && git commit -m'Add first 2500 images' && git push
cp ../merged/image25*.jpg content/images/ && git add . && git commit -m'Add first 2600 images' && git push
cp ../merged/image26*.jpg content/images/ && git add . && git commit -m'Add first 2700 images' && git push
cp ../merged/image27*.jpg content/images/ && git add . && git commit -m'Add first 2800 images' && git push
cp ../merged/image28*.jpg content/images/ && git add . && git commit -m'Add first 2900 images' && git push
cp ../merged/image29*.jpg content/images/ && git add . && git commit -m'Add first 3000 images' && git push
